language: swift
os: osx

git:
  depth: 1

stages:
  - name: test

jobs:
  include:
    - stage: test
      name: Run Unit Tests (iOS 10.3.1, iPhone 5s)
      osx_image: xcode11.5
      xcode_workspace: ParselyDemo.xcworkspace
      xcode_scheme: ParselyTrackerTests
      xcode_destination: platform=iOS Simulator,OS=10.3.1,name=iPhone 5s
      before_install:
        - pod repo update
    - stage: test
      name: Run Unit Tests (iOS 11.4, iPhone X)
      osx_image: xcode11.5
      xcode_workspace: ParselyDemo.xcworkspace
      xcode_scheme: ParselyTrackerTests
      xcode_destination: platform=iOS Simulator,OS=11.4,name=iPhone X
      before_install:
        - pod repo update
