name: iOS starter workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  buildAndTest:
    name: Build and Test
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          - xcode: "13.2"
            ios: "15.2"
          - xcode: "14.1"
            ios: "16.1"
    name: test iOS (${{ matrix.ios }})
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v2
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_$.app && /usr/bin/xcodebuild -version
    - name: CocoaPod Install
      run: pod install
    - name: Build and Test
      run: |
        xcodebuild test -workspace ParselyDemo.xcworkspace -scheme ParselyTrackerTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12,OS=$' | xcpretty && exit ${PIPESTATUS[0]}
