name: iOS starter workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  buildAndTest:
    name: Build and Test
    strategy:
      matrix:
        include:
          # Only using "latest" CI for the moment.
          # We'll decide later whether to keep running tests on older environments
          #
          # - macos: "macos-10.15"
          #   xcode: "11.6"
          #   ios: "13.6"
          #   iphone: "iPhone 11"
          # - macos: "macos-11"
          #   xcode: "12.4"
          #   ios: "14.4"
          #   iphone: "iPhone 12"
          - macos: "macos-12"
            xcode: "14.1"
            ios: "16.1"
            iphone: "iPhone 14"
    runs-on: ${{ matrix.macos }}
    steps:
    - uses: actions/checkout@v3
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ matrix.xcode }}
    - name: Build and Test
      run: make test
