name: iOS starter workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  buildAndTest:
    name: Build and Test
    strategy:
      matrix:
        include:
          - macos: "macos-10.15"
            xcode: "10.3"
            ios: "12.4"
            iphone: "iPhone 8"
          - macos: "macos-10.15"
            xcode: "11.6"
            ios: "13.6"
            iphone: "iPhone 11"
          - macos: "macos-11"
            xcode: "12.4"
            ios: "14.4"
            iphone: "iPhone 12"
          - macos: "macos-12"
            xcode: "14.1"
            ios: "16.1"
            iphone: "iPhone 14"
    runs-on: ${{ matrix.macos }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v2
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ matrix.xcode }}
    - name: CocoaPod Install
      run: pod install
    - name: Build and Test
      run: |
        xcodebuild test -workspace ParselyDemo.xcworkspace -scheme ParselyTrackerTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=${{ matrix.iphone }},OS=${{ matrix.ios }}' | xcpretty && exit ${PIPESTATUS[0]}
