name: iOS starter workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  buildAndTest:
    name: Build and Test
    strategy:
      matrix:
        include:
          # Only using "latest" CI for the moment.
          # We'll decide later whether to keep running tests on older environments
          - macos: "latest"
    runs-on: ${{ matrix.macos }}
    steps:
    - uses: actions/checkout@v3
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ matrix.xcode }}
    - name: Build and Test
      run: make test
